### PR TITLE
Update Scala.js to 1.1.0

### PR DESCRIPTION
**Pull request by lolgab**
I want to update my [scala-fullstack](https://github.com/lolgab/scala-fullstack) example to latest Scala.js and Laminar :-)

### CODE REVIEW

**Comment by cornerman** [comment]
@lolgab Awesome! Thank you :)

I just updated akka on master to fix the build error in travis. So could you please rebase on master? Will merge and release then!

**Comment by lolgab** [comment]
I was doing the same :-)
Rebased right now :)

**Comment by cornerman** [comment]
Perfect :+1:

**Comment by cornerman** [comment]
Actually, I have never released this on maven, but only used jitpack. Is that good enough or would you prefer a maven release?

**Comment by lolgab** [comment]
I'm totally fine. I was using it from covenant, which is itself released on jitpack.
Maybe if you're going to maintain and evolve the libraries it would be cool to see them on maven central.
For my example repo it's fine either way :)

**Comment by cornerman** [comment]
Great - then it is good. I have plans for another take on covenant and this, but it was difficult to find the time. Will eventually do it and make a release :)

**Pull request merged**
